---
# configure base dependencies for piep

- name: make sure node ppa is available
  apt_repository: repo='ppa:chris-lea/node.js'

- name: update apt-cache if needed
  apt: update_cache=yes

- name: make sure nodejs is installed
  apt: name=nodejs state=present

- name: make sure git is installed
  apt: name=git state=present

- name: make sure nginx is installed
  apt: name=nginx state=present

- name: make sure psycopg2 is installed (for Ansible psql modules)
  apt: name=python-psycopg2

- name: make sure postgresql is installed
  apt: name=postgresql state=present
  environment:
    LC_ALL: en_US.UTF-8

- name: make sure postgresql contrib extensions are installed
  apt: name=postgresql-contrib state=present
